### ISSUE TITLE
Phaser limited to maximum two haplotypes per contig?

### ISSUE THREAD

**Issue by mscharmann** [secastel/phaser#19]
Do I understand it correctly that phaser.py will at maximum detect two different haplotypes per contig?
This is reasonable for perfect unambiguous mapping in diploids, but a severe limitation if (a) the genome / transcriptome is indeed polyploid (or a pool of individuals), and (b) reads from paralog loci were mapped to the same reference contig. In both cases, >2 haplotypes can be possible from a single sample.

**Comment by secastel** [comment]
You are correct, phASER is designed to work with diploid genomes. To my knowledge this is the same for all existing read backed phasing methods. I realize that this is an issue for polyploid genomes, but unfortunately there are no plans at the moment to include support for polyploids. The tool should not be run on pooled individuals, because the goal is not to identify and assemble all of the possible haplotypes observed in a pool, but instead to output the 2 most likely haplotypes a single individual.

In the case of reads mapping ambiguously to the reference contig, it is highly advisable to use a MAPQ filter sufficiently high such that only uniquely aligned reads are used. If you are aligning to contigs with many paralogs then I would suggest aligning with stringent settings (e.g. reduce the number of mismatches allowed, increase penalties, etc...). Again, phASER will always assume for a given contig there are only 2 true haplotypes. If you have many paralogous transcripts they should each be represented by their own contig with some level of genetic variation to distinguish them that allows reads to map unambiguously.

**Comment by colindaven** [comment]
This idea of doing read backed phasing of pools of individuals comes up again and again. Are there any tools which can handle this ?

**Comment by secastel** [comment]
Not that I know of, but to be honest, I've never had to do this, so I haven't really looked.
