### ISSUE TITLE
Pseudogenomes

### ISSUE THREAD

**Issue by colindaven** [secastel/phaser#5]
Hi,

quick question : should read alignments in BAM format and SNP calls in VCF be from alignments to pseudogenomes ? By pseudogenomes I mean genomes in which SNPs have been inserted to avoid too much reference bias, which is a known problem for these types of analyses.

Or is it OK if the BAM and VCF are from alignments to the reference sequence ?

Thanks!
Colin

**Comment by secastel** [comment]
Hi Colin,
It shouldn't make a difference which reference you aligned the reads to, since what phASER does is to compare the base in the reads to whatever is listed as REF / ALT in the provided VCF. The only important thing is that the coordinates and bases in the VCF match to whatever reference was used for read alignment. So you can definitely use reads aligned to the reference sequence without any issue. In fact this is what we used for all our test cases, since the vast majority of users will probably simply align to the reference.

Hope this helps.

Stephane
