### ISSUE TITLE
--chr option, crashing and a possible bug

### ISSUE THREAD

**Issue by colindaven** [secastel/phaser#7]
Hi,

I would really recommend the --chr option for RNA-seq datasets from plant genomes - this one is ca. 750MB so relatively small.

On 512gb and 2TB RAM servers I was never getting past step 5 for whole genomes
"5. Phasing blocks...
     phasing large (>15 variants) blocks...
"

It would just killed by the server after apparently spiralling mem usage after 12-24 hrs.

If I pass the --chr option most chromosomes are done after 2-6 hours. 

There may be a bug with --chr by the way. It seems I get a VCF for chromosome5 called eg "test21_chr5.vcf", but it contains SNPs from all chromosomes eg 1-9, eg, not just phased SNPs for chr5.

Is this a known bug ?

Also - can I just combine the *haplotypic_counts.txt files from each chromosome and use them as input for the next step "phaser_gene_ae.py" ?  I hope this will work.

Thanks,
Colin

**Comment by secastel** [comment]
Hi Colin,
Strange about phASER hanging with such a small input RNA-seq BAM. Off the top of my head I'm not sure what could be causing that, but I'll give it some thought.

As for the VCF produced with --chr, yes I agree that when using this option the output VCF should only contain the chromosome specified, so I will fix this.

As for the haplotypic counts, yes you should be able to combine them, provided there is only a single header with all the data, IE don't just "cat *.haplotypic_counts.txt > all.haplotypic_counts.txt" as this won't work with phaser_gene_ae. One thing to note about the gene_ae script, is that it assumes you used a phased VCF as an input to the initial phASER run. If this isn't the case then it won't run, since it doesn't know the phasing of SNPs that weren't phased with phASER relative to each other. I have been meaning to add an option to the script that would allow for this case, by for example, choosing the haplotypic block or SNP with the highest coverage as representative of the gene. Let me know if this applies to you, and if so I will push out an update to phaser_gene_ae.py.

Stephane

**Comment by colindaven** [comment]
Hi Stephane,

the genome is 750mb, the RNA-seq BAM I am using is 6.7Gb.

I am using prephased data in some experiments, but not in others, and or I cannot guarantee that the phasing is absolutely perfect, so an additional option for the phaser_gene_ae.py script would be very useful. Thanks!


A phaser run on one of the chromosomes is now crashing with the following error ...
sorry, I can't supply the test data BAMs.


     phasing large (>15 variants) blocks...
Traceback (most recent call last):
  File "/home/bioinformatics/NAS01/programs/phaser/phaser/phaser/phaser.py", line 1839, in <module>
    main();
  File "/home/bioinformatics/NAS01/programs/phaser/phaser/phaser/phaser.py", line 733, in main
    pool_output = parallelize(count_hap_reads, pool_input);
  File "/home/bioinformatics/NAS01/programs/phaser/phaser/phaser/phaser.py", line 1645, in parallelize
    pool_output = pool.map(function, pool_input);
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
IOError: bad message length


Best wishes,
Colin

**Comment by secastel** [comment]
I see. All of our testing was done on human, which is a much larger genome, so I don't think the genome size of your organism is the issue, but it is possible that the SNP density of your data is much higher, which would result in many blocks with high numbers of variants.

The error you saw is the result of a limitation in the way python pipes data back from spawned processes back to the main process during multiprocessing. Basically at this step there is just too much data being shuttled between the processes to be handled by the piping. It sounds counterintuitive, but for those samples which failed I would try running again with "--threads 1". Doing this will take longer, but the advantage is that no data will need to be piped between processes, and it should prevent this error.

Thanks for reporting these bugs, and keep on the lookout for new versions of phASER in the near future that will address some of these issues.

**Comment by secastel** [comment]
The latest commit for phaser_gene_ae.py has a new argument "--no_gw_phase" which should be useful in situations when the input VCF to phaser was not phased.

**Comment by colindaven** [comment]
Thanks for your efforts. I'll test the script phaser_gene_ae.py soon.

I'll do my best to recreate test bams using public data if you're interested, but I don't know if the same errors will occur. At the moment the main holdup is waiting on two chromosomes to finish, but I don't think they will (7 others are done).

I have checked the SNP density over all chromosomes, the two which have not finished don't seem to have notably more dense SNPs. 

For a 500kbp sliding window with vcftools --SNPdensity
summary(d$VARIANTS.KB) 
 Max. 2.1240  variants per KB

**Comment by secastel** [comment]
Hmm, not sure what is causing the slowdown as it doesn't seem like you have any really variant dense regions... I would be more than happy to look into it myself if you can provide some test case data and I can reproduce the slowdown. Phasing a whole human genome with dense genotyping and ~50 million RNA-seq reads takes under 20 minutes using 4 threads in my testing, so the speeds you are seeing are really pathologically slow. This suggests to me that something odd is going on.

**Comment by colindaven** [comment]
Sorry about the wait, I have been attempting to generate a test case amongst many other projects!

This is RNA-seq data from a public genotype. I generated a VCF file from an alignment of RNA-seq reads to the reference genome. 



##################################################
              Welcome to phASER v0.4
  Author: Stephane Castel (scastel@nygenome.org)
##################################################

#1. Loading heterozygous variants into intervals...
     loading VCF into memory...
     parsing VCF...
          37120 of 42402 heterozygoys sites being used for phasing (5282 indels excluded, 0 blacklisted variants)
     creating genomic intervals...
#2. Retrieving reads that overlap heterozygous sites...
     Reads are being written to disk, this will impact performance.
     file: ../SRR1699442_1_s.bam
          minimum mapq: 1
          retrieved 0 reads
          assigning reads to variants...
     FATAL ERROR: No reads could be matched to variants. Please double check your settings and input files. Common reasons for this occurring include: 1) MAPQ or BASEQ set too conservatively 2) BAM and VCF have different chromosome names (IE 'chr1' vs '1').

However, I checked this problem, and can't solve it (have tried assding PASS to filter in the VCF file etc and juggling parameters, MQ etc a bit. I even put them in a genome browser, and the reads match to the VCF positions.

VCF generated by freebayes:
`
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  DP02
SBK1v2  10655   .       T       C       1058.47 PASS    AB=0;ABP=0;AC=2;AF=1;AN=2;AO=36;CIGAR=1X;DP=36;DPB=36;DPRA=0;EPP=14.8328;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=255;MQMR=0;
NS=1;NUMALT=1;ODDS=54.5118;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1289;QR=0;RO=0;RPL=29;RPP=32.2045;RPPR=0;RPR=7;RUN=1;SAF=30;SAP=37.7539;SAR=6;SRF=0;SRP=0;SRR=0;TYPE
=snp    GT:DP:DPR:RO:QR:AO:QA:GL        1/1:36:36,36:0:0:36:1289:-116.368,-10.8371,0
SBK1v2  12050   .       G       A       448.635 PASS    AB=0.825;ABP=39.7082;AC=1;AF=0.5;AN=2;AO=33;CIGAR=1X;DP=40;DPB=40;DPRA=0;EPP=10.9724;EPPR=3.32051;GTI=0;LEN=1;MEANALT
=1;MQM=163.364;MQMR=255;NS=1;NUMALT=1;ODDS=4.39545;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1220;QR=262;RO=7;RPL=27;RPP=32.0291;RPPR=3.32051;RPR=6;RUN=1;SAF=7;SAP=26.76
49;SAR=26;SRF=0;SRP=18.2106;SRR=7;TYPE=snp      GT:DP:DPR:RO:QR:AO:QA:GL        0/1:40:40,33:7:262:33:1220:-60.469,0,-11.9131
SBK1v2  12068   .       T       C       9.13373e-12     PASS    AB=0.65;ABP=6.91895;AC=1;AF=0.5;AN=2;AO=13;CIGAR=1X;DP=20;DPB=20;DPRA=0;EPP=31.2394;EPPR=18.2106;GTI=0;LEN=1;
MEANALT=1;MQM=22.3846;MQMR=255;NS=1;NUMALT=1;ODDS=26.8881;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=491;QR=280;RO=7;RPL=12;RPP=23.2217;RPPR=18.2106;RPR=1;RUN=1;SAF=1;SAP
=23.2217;SAR=12;SRF=0;SRP=18.2106;SRR=7;TYPE=snp        GT:DP:DPR:RO:QR:AO:QA:GL        0/1:20:20,13:7:280:13:491:-0.966121,0,-19.5794
`

The BAM has alignments vs chromosome "SBK1v2" etc.

`
SRR1699442.3333983      0       SBK1v2  10389   3       27M2I61M        *       0       0       CTGCTGGGAAATTGGTAAAATTTTGCGTTTTTTTTTGTTAAATGCGCTTCTTTATTTTCTCGACGTTTATTGGTGATTTGGTGTTCTTTT     CCCFFFFFHHGHHJIFHIJJJJJJJJJJJJJJJJJJGHIHIJIIJFHHFFFFEDEEEEEEDDCDDBBCBDDCD@?CADEDD?@A@CDDDD      NH:i:2  HI:i:1  nM:i:9  AS:i:62
`

Any ideas?  I can make data available but hope to get to the real problem described previously where large blocks cannot be phased.

Thanks,
Colin

**Comment by secastel** [comment]
Hi Colin,
No problem about the wait. As for the specific problem you mentioned above, it is difficult for me to figure out what is going on without the files. My guess is that there is something off in the BAM. If you are able to make the files available I can try to figure out what is going on. You could for example extract just a single chromosome's worth of data. If you are able to do this please let me know, and I can setup a way for you to transfer it to me if needed.

As for the problem of large blocks being phased, I've been working on a new version of the haplotype assembler, and in my hands it runs up to 50x faster than the old version. It also takes much less memory. I'm hoping to have this done and pushed to github in the next few weeks, so if you don't mind waiting it might be best to try that when it is available and see if it fixes your problem.

Best,
Stephane

**Comment by colindaven** [comment]
Hi Stephane,

great news to hear about a novel block phaser being developed. Congrats.

I added a test case on google drive and sent you an invite.

"
Test case for Phaser on a plant genome (currently the public version on free release consists of scaffolds).

## This is _unphased_ data and no phasing can be done for this dataset. My own unpublished datasets do have phased VCFs since I have  parental information.

Hope this helps for diagnosis/testing.
Should be 
.bam
.bai
shell script with the attempted command
vcf.gz (non phased, could this be the problem)
vcf.gz.tbi

"

The error I was having with this was:

              Welcome to phASER v0.4
  Author: Stephane Castel (scastel@nygenome.org)
##################################################

#1. Loading heterozygous variants into intervals...
     loading VCF into memory...
     parsing VCF...
          38397 of 43846 heterozygoys sites being used for phasing (5449 indels excluded, 0 blacklisted variants)
     creating genomic intervals...
#2. Retrieving reads that overlap heterozygous sites...
     Reads are being written to disk, this will impact performance.
     file: ../SRR1699442_1_s_calmd.bam
          minimum mapq: 1
          retrieved 0 reads
          assigning reads to variants...
     FATAL ERROR: No reads could be matched to variants. Please double check your settings and input files. Common reasons for this occurring include: 1) MAPQ or BASEQ set too conservatively 2) BAM and VCF have different chromosome names (IE 'chr1' vs '1').


Thanks for looking at this.

Colin

**Comment by secastel** [comment]
Hi Colin,
Thanks so much for making these test files available, and for taking the time to let me know about these issues. I really appreciate it, and I think it has made a big contribution to phASER.

I figured out what the issue is. First thing you will need to do is pull the latest version of phASER from github.

This version includes the following arguments, that you will need to set, and will allow phASER to run successfully on your data.

--id_separator '-'
By default phASER uses '\_' as a separator when generating unique IDs. If this character is present in the chromosome name it will mess a few things up. There is a new option which allows you to change the separator, so you can change it to, for example '-', by including the argument above.

--paired_end 0
The old version of phASER was requiring reads to have the "read mapped in proper pair" flag (2), which is of course not set for single end reads, so was resulting in all reads being filtered. Setting the above argument should address this.

So, try updating to the latest version (0.6), and see if adding those two arguments solves your problem.

FYI using the new version, phasing completed using only a single thread and ~ 2GB of RAM in 328 seconds, so I think you'll find the performance is hugely improved in the new version.

Here is the command I used to call phASER, and attached is the run log for your reference.

python2.7 ../phaser
[cd_phaser_log.txt](https://github.com/secastel/phaser/files/270828/cd_phaser_log.txt)
.py --vcf SRR1699442_freebayes_ORIG.vcf.gz --bam SRR1699442_1_s_calmd.bam --mapq 255 --baseq 10 --o cd_test --sample DP02 --id_separator '-' --pass_only 0 --paired_end 0

Thanks again for bringing this to my attention, really hope we can get this working for you.

Stephane

**Comment by colindaven** [comment]
Hi Stephane,

great, thanks a million for this. The new version has nicer logging and vastly improved performance. There is now no need for me to analyze single chromosomes at once. Also, the following gene level result collation step works perfectly as well. 

I think now we're at a stage where we can apply the algorithm more widely across samples, thanks for your hard work here.

Best wishes,
Colin
